database:
  type: 'SQLite'
  mysql:
    host: 'localhost'
    port: 3306
    database: 'minecraft'
    username: 'root'
    password: 'password'

mobs:
  ZOMBIE:
    min-coins: 1.5
    max-coins: 4.0
  SKELETON:
    min-coins: 1.5
    max-coins: 5.0
  BLAZE:
    min-coins: 3.0
    max-coins: 7.0
  ENDERMAN:
    min-coins: 6.0
    max-coins: 12.0
  CREEPER:
    min-coins: 4.0
    max-coins: 8.0
  IRON_GOLEM:
    min-coins: 6.0
    max-coins: 14.0
