database:
  type: 'SQLite'
  mysql:
    host: 'localhost'
    port: 3306
    database: 'minecraft'
    username: 'root'
    password: 'password'

mobs:
  ZOMBIE:
    min-coins: 1.5
    max-coins: 4.0
  SKELETON:
    min-coins: 1.5
    max-coins: 5.0
  BLAZE:
    min-coins: 3.0
    max-coins: 7.0
  ENDERMAN:
    min-coins: 6.0
    max-coins: 12.0
  CREEPER:
    min-coins: 4.0
    max-coins: 8.0
  IRON_GOLEM:
    min-coins: 6.0
    max-coins: 14.0

shop:
  rotation-times:
    normal: ["15:00", "15:10"]
    premium: ["15:05"]

  items:
    1:
      displayname: "&7Super miecz"
      material: DIAMOND_SWORD
      amount: 1
      stock: 10
      price: 10.0
      lore:
        - "&2Super ostry"
        - "&7Został wykonany przez..."
      command: "give %player% diamond_sword 1"
    2:
      displayname: "&7Ekskluzywny eliksir"
      material: DIRT
      amount: 1
      stock: 5
      price: 10.0
      lore:
        - "&2Super Dirt"
        - "&7Został wykonany przez..."
      command: "give %player% dirt 1"
    3:
      displayname: "&7Blyszczacy diament"
      material: DIAMOND
      amount: 5
      stock: 20
      price: 10.0
      lore:
        - "&bCzysty jak łza"
        - "&7Niesamowity skarb!"
      command: "give %player% diamond 5"
    4:
      displayname: "&7Niezniszczalny kilof"
      material: DIAMOND_PICKAXE
      amount: 1
      stock: 8
      price: 10.0
      lore:
        - "&bKopie na głębokość"
        - "&7Moc w twoich rękach"
      command: "give %player% diamond_pickaxe 1"
    5:
      displayname: "&7Zlote jablko"
      material: GOLDEN_APPLE
      amount: 3
      stock: 12
      price: 10.0
      lore:
        - "&6Krzepiący przysmak"
        - "&7Ozdoba każdego ekwipunku"
      command: "give %player% golden_apple 3"
    6:
      displayname: "&7Eliksir leczenia"
      material: POTION
      amount: 1
      stock: 15
      price: 10.0
      lore:
        - "&cPrzywraca zdrowie"
        - "&7Pij z umiarem"
      command: "give %player% potion{Potion:\"minecraft:healing\"} 1"
    7:
      displayname: "&7Wzmocniony luk"
      material: BOW
      amount: 1
      stock: 5
      price: 10.0
      lore:
        - "&9Dla prawdziwych łowców"
        - "&7Został wykonany przez elfy..."
      command: "give %player% bow 1"
    8:
      displayname: "&7Niewidzialna tarcza"
      material: SHIELD
      amount: 1
      stock: 6
      price: 10.0
      lore:
        - "&cNiewidoczna, ale ochroni cię"
        - "&7Została zaklęta przez..."
      command: "give %player% shield 1"
    9:
      displayname: "&7Mikstura szybkosci"
      material: POTION
      amount: 1
      stock: 10
      price: 10.0
      lore:
        - "&bBiegaj jak wiatr"
        - "&7Przygotowana przez czarodziejów..."
      command: "give %player% potion 1"

  categories:
    normal: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    premium: [2, 5, 6, 8, 9]

